def get_never_have_i_evers():
    return [
        "Never have I ever broken a bone.",
        "Never have I ever gotten a papercut from a book.",
        "Never have I ever stayed up all night.",
        "Never have I ever gotten lost in a mall.",
        "Never have I ever missed an important event.",
        "Never have I ever eaten something off the floor.",
        "Never have I ever been in a talent show.",
        "Never have I ever forgotten my homework.",
        "Never have I ever walked into the wrong classroom.",
        "Never have I ever sung in the shower.",
        "Never have I ever laughed so hard I cried.",
        "Never have I ever tripped in public.",
        "Never have I ever blamed a sibling for something I did.",
        "Never have I ever been on a roller coaster.",
        "Never have I ever played a prank on someone.",
        "Never have I ever gotten detention.",
        "Never have I ever made a snow angel.",
        "Never have I ever gotten caught daydreaming in class.",
        "Never have I ever been on a sports team.",
        "Never have I ever gotten stage fright.",
        "Never have I ever lost my lunch money.",
        "Never have I ever been stung by a bee.",
        "Never have I ever built a fort out of blankets.",
        "Never have I ever peed in a pool.",
        "Never have I ever forgotten a friend's birthday.",
        "Never have I ever laughed at the wrong moment.",
        "Never have I ever worn mismatched socks.",
        "Never have I ever gotten lost in a store.",
        "Never have I ever dropped my phone in water.",
        "Never have I ever waved at someone who wasn't waving at me.",
        "Never have I ever lost a library book.",
        "Never have I ever accidentally called a teacher 'Mom' or 'Dad'.",
        "Never have I ever spilled something on myself in public.",
        "Never have I ever cried during a movie.",
        "Never have I ever met a celebrity.",
        "Never have I ever been afraid of the dark.",
        "Never have I ever built a sandcastle.",
        "Never have I ever played video games all night.",
        "Never have I ever worn pajamas all day.",
        "Never have I ever watched cartoons as a teenager.",
        "Never have I ever been to a school dance.",
        "Never have I ever made a TikTok or YouTube video.",
        "Never have I ever forgotten my own phone number.",
        "Never have I ever eaten a whole pizza by myself.",
        "Never have I ever laughed so hard I snorted.",
        "Never have I ever been on a plane.",
        "Never have I ever broken a piece of furniture by sitting on it.",
        "Never have I ever had food stuck in my teeth all day.",
        "Never have I ever accidentally sent a text to the wrong person.",
        "Never have I ever won a contest.",
        "Never have I ever been outside of my country.",
        "Never have I ever accidentally worn someone else's clothes.",
        "Never have I ever gotten gum stuck in my hair.",
        "Never have I ever pulled an all-nighter for an exam.",
        "Never have I ever had a pet fish.",
        "Never have I ever walked into a glass door.",
        "Never have I ever forgotten where I parked my car.",
        "Never have I ever fallen off my bike.",
        "Never have I ever laughed during a serious moment.",
        "Never have I ever eaten something I knew was expired.",
        "Never have I ever gotten a haircut I didn't like.",
        "Never have I ever accidentally used someone else's toothbrush.",
        "Never have I ever mistaken a stranger for someone I knew.",
        "Never have I ever been on a waterslide.",
        "Never have I ever eaten a bug by accident.",
        "Never have I ever been in a parade.",
        "Never have I ever spilled water while trying to drink it.",
        "Never have I ever gotten my shoe stuck in mud.",
        "Never have I ever forgotten an important event.",
        "Never have I ever borrowed something and never returned it.",
        "Never have I ever used a fake excuse to get out of something.",
        "Never have I ever drawn on someone's face while they were sleeping.",
        "Never have I ever played hide and seek as a teenager.",
        "Never have I ever been to a sleepover.",
        "Never have I ever fallen off a chair.",
        "Never have I ever worn my clothes inside out by accident.",
        "Never have I ever tried to learn a dance from the internet.",
        "Never have I ever done a magic trick.",
        "Never have I ever accidentally deleted an important file.",
        "Never have I ever been the last one picked for a team.",
        "Never have I ever gotten sunburnt.",
        "Never have I ever been on a boat.",
        "Never have I ever broken something and blamed it on someone else.",
        "Never have I ever been scared of a movie as a kid.",
        "Never have I ever accidentally said 'I love you' to someone by mistake.",
        "Never have I ever had a funny nickname.",
        "Never have I ever forgotten my backpack at school.",
        "Never have I ever been in a food fight.",
        "Never have I ever been on a road trip.",
        "Never have I ever been chased by an animal.",
        "Never have I ever lost a bet.",
        "Never have I ever seen snow in real life.",
        "Never have I ever baked cookies from scratch.",
        "Never have I ever accidentally broken a plate or glass.",
        "Never have I ever danced in the rain.",
        "Never have I ever been scared of clowns.",
        "Never have I ever laughed at a joke I didn't get.",
        "Never have I ever made a silly face in a serious photo.",
        "Never have I ever eaten food that was meant for a pet.",
        "Never have I ever been the teacher's favorite.",
        "Never have I ever forgotten my lunch at home.",
        "Never have I ever wished on a shooting star.",
        "Never have I ever cried from laughing too hard.",
        "Never have I ever been on a Ferris wheel.",
        "Never have I ever played a board game all the way through.",
        "Never have I ever accidentally ruined a surprise.",
        "Never have I ever lost a piece of a puzzle.",
        "Never have I ever climbed a mountain.",
        "Never have I ever worn sunglasses indoors."
    ]

def get_brain_teasers():
    return [
        "I have keys but no locks. I have space but no room. You can enter, but you can't go outside. What am I?",
        "What comes once in a minute, twice in a moment, but never in a thousand years?",
        "I can be cracked, made, told, and played. What am I?",
        "I am always hungry, I must always be fed. The finger I touch, will soon turn red. What am I?",
        "What has a head, a tail, but no body?",
        "I speak without a mouth and hear without ears. I have nobody, but I come alive with wind. What am I?",
        "I have cities, but no houses. I have forests, but no trees. I have water, but no fish. What am I?",
        "What can travel around the world while staying in a corner?",
        "What has lots of eyes, but can’t see?",
        "What has many needles, but doesn’t sew?",
        "What has hands, but can’t clap?",
        "What has one eye, but can’t see?",
        "What has many keys, but can’t open a single lock?",
        "What has words, but never speaks?",
        "What runs all around a backyard, yet never moves?",
        "What can fill a room but takes up no space?",
        "If you drop me, I’m sure to crack, but give me a smile and I’ll always smile back. What am I?",
        "The more you take, the more you leave behind. What are they?",
        "I am always in front of you but can’t be seen. What am I?",
        "What breaks yet never falls, and what falls yet never breaks?",
        "I can fly without wings. I cry without eyes. Whenever I go, darkness flies. What am I?",
        "I have branches, but no fruit, trunk or leaves. What am I?",
        "What can you catch, but not throw?",
        "I get wetter the more I dry. What am I?",
        "I am taken from a mine, and shut in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?",
        "I have no life, but I can die. What am I?",
        "I can be long, I can be short. I can grow, I can die. I can laugh, I can cry. What am I?",
        "I come from a mine and get surrounded by wood always. Everyone uses me. What am I?",
        "I can be cracked, made, told, and played. What am I?",
        "I can run but not walk. Wherever I go, thought follows close behind. What am I?",
        "I am invisible, weigh nothing, and if you put me in a barrel, it will become lighter. What am I?",
        "I fly without wings. I cry without eyes. Wherever I go, darkness flies. What am I?",
        "I am full of holes but I still hold water. What am I?",
        "What gets bigger the more you take away?",
        "What comes once in a year, twice in a month, four times in a week, and six times in a day?",
        "What belongs to you but others use it more than you do?",
        "I can be cracked, made, told, and played. What am I?",
        "The more of this there is, the less you see. What is it?",
        "I am always coming, but never arrive. What am I?",
        "If you have me, you want to share me. If you share me, you don’t have me. What am I?",
        "What can you hold in your left hand, but not in your right?",
        "What can be seen once in a minute, twice in a moment, and never in a thousand years?",
        "What is always in front of you but can’t be seen?",
        "What has to be broken before you can use it?",
        "I am not alive, but I grow. I don’t have eyes, but I can cry. What am I?",
        "I can be flipped and broken but I never move. I can be closed and open, and sometimes I am curved. What am I?",
        "What begins with T, finishes with T, and has T in it?",
        "What is so fragile that saying its name breaks it?",
        "What comes once in a year, twice in a month, four times in a week, and six times in a day?",
        "I have keys but no locks. I have space but no rooms. You can enter, but you can’t go outside. What am I?",
        "What goes up but never comes down?",
        "What is always in front of you but can’t be seen?",
        "What has many teeth but can’t bite?",
        "What has a head, a tail, but no body?",
        "What gets wet while drying?",
        "I have keys but no locks. I have space but no rooms. You can enter, but you can’t go outside. What am I?",
        "What has one eye, but can’t see?",
        "What has many needles, but doesn’t sew?",
        "What can travel around the world while staying in a corner?",
        "What has legs, but doesn’t walk?",
        "What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?",
        "What comes down but never goes up?",
        "I have teeth but can’t eat. What am I?",
        "What has a neck but no head?",
        "What can be cracked, made, told, and played?",
        "What has words but never speaks?",
        "What has an eye but cannot see?",
        "What has a heart that doesn’t beat?",
        "I am not alive but I can grow. I don’t have eyes but I can cry. What am I?",
        "What has keys but can’t open locks?",
        "What can fill a room but takes no space?",
        "I am taken from a mine and shut in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?",
        "I am full of holes but I still hold water. What am I?",
        "What belongs to you but others use it more than you do?",
        "What gets bigger the more you take away?",
        "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?",
        "What has an eye but cannot see?",
        "What has many keys but can’t open a single lock?",
        "What runs all around a backyard, yet never moves?",
        "What has words, but never speaks?",
        "What can travel around the world while staying in a corner?",
        "I have branches, but no fruit, trunk or leaves. What am I?",
        "What is so fragile that saying its name breaks it?",
        "What is always coming but never arrives?",
        "What can you hold in your left hand, but not in your right?",
        "I get wetter the more I dry. What am I?",
        "I am always in front of you but can’t be seen. What am I?",
        "What breaks yet never falls, and what falls yet never breaks?",
        "What comes once in a year, twice in a month, four times in a week, and six times in a day?",
        "What is always coming but never arrives?",
        "What belongs to you but others use it more than you do?",
        "What has many teeth but can’t bite?",
        "I can run but not walk. Wherever I go, thought follows close behind. What am I?",
        "What can fill a room but takes no space?",
        "What can you catch, but not throw?",
        "What is full of holes but still holds water?"
    ]

def get_brain_teaser_answers():
    return [
        "A keyboard",
        "The letter 'M'",
        "A joke",
        "Fire",
        "A coin",
        "An echo",
        "A map",
        "A stamp",
        "A potato",
        "A Christmas tree",
        "A clock",
        "A needle",
        "A piano",
        "A book",
        "A fence",
        "Light",
        "A mirror",
        "Footsteps",
        "The future",
        "Day and night",
        "A cloud",
        "A bank",
        "A cold",
        "A towel",
        "A pencil",
        "A battery",
        "A hair",
        "A pencil",
        "A joke",
        "A nose",
        "A hole",
        "A hole",
        "A sponge",
        "A shadow",
        "The letter 'E'",
        "Your name",
        "A joke",
        "Darkness",
        "Tomorrow",
        "A secret",
        "Your right hand",
        "The letter 'M'",
        "The future",
        "An egg",
        "A candle",
        "A page",
        "A teapot",
        "Silence",
        "The letter 'E'",
        "A keyboard",
        "Your age",
        "The future",
        "A comb",
        "A coin",
        "A towel",
        "A keyboard",
        "A needle",
        "A stamp",
        "A table",
        "A river",
        "Rain",
        "A saw",
        "A bottle",
        "An egg",
        "A book",
        "A needle",
        "A playing card",
        "A heart",
        "A candle",
        "A keyboard",
        "Light",
        "A pencil",
        "A sponge",
        "Your name",
        "A hole",
        "Fire",
        "A needle",
        "A piano",
        "A fence",
        "A book",
        "A stamp",
        "A bank",
        "Silence",
        "Tomorrow",
        "Your right hand",
        "A towel",
        "The future",
        "Day and night",
        "The letter 'E'",
        "Tomorrow",
        "Your name",
        "A comb",
        "A river",
        "Light",
        "A cold",
        "A sponge"
    ]

def get_quiz_questions():
    return {
        "What is the capital of France?": "Paris",
        "Who wrote 'To Kill a Mockingbird'?": "Harper Lee",
        "What is the largest planet in our solar system?": "Jupiter",
        "How many continents are there on Earth?": "Seven",
        "What is the square root of 64?": "8",
        "Who painted the Mona Lisa?": "Leonardo da Vinci",
        "What is the smallest country in the world?": "Vatican City",
        "Which element has the chemical symbol 'O'?": "Oxygen",
        "What is the longest river in the world?": "Nile",
        "Who discovered gravity?": "Isaac Newton",
        "What is the tallest mountain in the world?": "Mount Everest",
        "Who developed the theory of relativity?": "Albert Einstein",
        "Which planet is known as the Red Planet?": "Mars",
        "How many sides does a hexagon have?": "Six",
        "What is the fastest land animal?": "Cheetah",
        "Who was the president of the United States under the Articles of Confederation?": "John Hanson",
        "What is the hardest natural substance on Earth?": "Diamond",
        "Which ocean is the largest?": "Pacific Ocean",
        "What is the chemical symbol for gold?": "Au",
        "Who invented the telephone?": "Alexander Graham Bell",
        "How many legs does a spider have?": "Eight",
        "What year did the Titanic sink?": "1912",
        "What is the main ingredient in guacamole?": "Avocado",
        "Who is the author of the Harry Potter series?": "J.K. Rowling",
        "What is the national animal of Australia?": "Kangaroo",
        "How many bones are in the adult human body?": "206",
        "Which planet is closest to the Sun?": "Mercury",
        "What is the chemical symbol for water?": "H2O",
        "Which is the only mammal capable of flight?": "Bat",
        "Who painted 'The Starry Night'?": "Vincent van Gogh",
        "What is the most spoken language in the world?": "English",
        "What is the currency of Japan?": "Yen",
        "Who was the first man to walk on the moon?": "Neil Armstrong",
        "How many hearts does an octopus have?": "Three",
        "What is the national sport of Canada?": "Lacrosse",
        "What is the largest organ in the human body?": "Skin",
        "What is the speed of light?": "299,792,458 meters per second",
        "Which is the only fruit with its seeds on the outside?": "Strawberry",
        "Who discovered penicillin?": "Alexander Fleming",
        "Which planet has the most moons?": "Saturn",
        "What is the boiling point of water in Celsius?": "100",
        "How many stripes are on the American flag?": "13",
        "What is the capital of Italy?": "Rome",
        "Which animal is known as the king of the jungle?": "Lion",
        "What is the powerhouse of the cell?": "Mitochondria",
        "How many wings does a butterfly have?": "Four",
        "Which gas do plants use for photosynthesis?": "Carbon Dioxide",
        "How many players are on a soccer team?": "11",
        "What year did World War II end?": "1945",
        "What is the deepest ocean in the world?": "Pacific Ocean",
        "Which instrument has 88 keys?": "Piano",
        "What is the national flower of Japan?": "Cherry Blossom",
        "Which gas makes up most of the Earth's atmosphere?": "Nitrogen",
        "What is the largest desert in the world?": "Antarctica",
        "Which blood type is the universal donor?": "O Negative",
        "Who wrote 'Romeo and Juliet'?": "William Shakespeare",
        "What is the capital of Brazil?": "Brasilia",
        "Which country is known as the Land of the Rising Sun?": "Japan",
        "How many planets are in the solar system?": "Eight",
        "What is the only even prime number?": "2",
        "Who invented the light bulb?": "Thomas Edison",
        "What is the most abundant gas in the universe?": "Hydrogen",
        "What is the largest land animal?": "Elephant",
        "Which ocean is the saltiest?": "Atlantic Ocean",
        "How many colors are in a rainbow?": "Seven",
        "Which mammal can hold its breath the longest?": "Sperm Whale",
        "What does DNA stand for?": "Deoxyribonucleic Acid",
        "Which metal is liquid at room temperature?": "Mercury",
        "What is the most common gas in the Earth's atmosphere?": "Nitrogen",
        "What is the longest bone in the human body?": "Femur",
        "Who discovered America?": "Christopher Columbus",
        "How many time zones does Russia have?": "11",
        "What is the closest star to Earth?": "The Sun",
        "Which country has the most pyramids?": "Sudan",
        "What is the world's smallest country by area?": "Vatican City",
        "Who painted 'The Last Supper'?": "Leonardo da Vinci",
        "What is the largest freshwater lake in the world?": "Lake Superior",
        "What is the national bird of the United States?": "Bald Eagle",
        "What is the capital of Canada?": "Ottawa",
        "Which element is needed for breathing?": "Oxygen",
        "What does HTTP stand for?": "HyperText Transfer Protocol",
        "Who was the first female pilot to fly solo across the Atlantic?": "Amelia Earhart",
        "What is the heaviest naturally occurring element?": "Uranium",
        "Which continent is the driest?": "Antarctica",
        "What is the study of earthquakes called?": "Seismology",
        "Which country is known for the Great Wall?": "China",
        "What is the currency of the United Kingdom?": "Pound Sterling",
        "Which vitamin is produced when sunlight hits the skin?": "Vitamin D",
        "What is the capital of Russia?": "Moscow",
        "Which gas is known as laughing gas?": "Nitrous Oxide",
        "What is the name of the first man-made satellite?": "Sputnik",
        "What is the coldest place on Earth?": "Antarctica",
        "Which is the only metal that is liquid at room temperature?": "Mercury",
        "What is the capital of India?": "New Delhi",
        "What is the largest reptile in the world?": "Saltwater Crocodile",
        "Which fruit contains the most vitamin C?": "Guava",
        "What is the capital of China?": "Beijing",
        "Who is known as the father of modern physics?": "Albert Einstein",
        "Which bird can fly backward?": "Hummingbird",
        "What is the capital of Germany?": "Berlin",
        "Which muscle in the body never stops working?": "Heart",
    }
