def get_never_have_i_evers():
    return
def get_brain_teasers():
    return [
        "I have keys but no locks. I have space but no room. You can enter, but you can't go outside. What am I?",
        "What comes once in a minute, twice in a moment, but never in a thousand years?",
        "I can be cracked, made, told, and played. What am I?",
        "I am always hungry, I must always be fed. The finger I touch, will soon turn red. What am I?",
        "What has a head, a tail, but no body?",
        "I speak without a mouth and hear without ears. I have nobody, but I come alive with wind. What am I?",
        "I have cities, but no houses. I have forests, but no trees. I have water, but no fish. What am I?",
        "What can travel around the world while staying in a corner?",
        "What has lots of eyes, but can’t see?",
        "What has many needles, but doesn’t sew?",
        "What has hands, but can’t clap?",
        "What has one eye, but can’t see?",
        "What has many keys, but can’t open a single lock?",
        "What has words, but never speaks?",
        "What runs all around a backyard, yet never moves?",
        "What can fill a room but takes up no space?",
        "If you drop me, I’m sure to crack, but give me a smile and I’ll always smile back. What am I?",
        "The more you take, the more you leave behind. What are they?",
        "I am always in front of you but can’t be seen. What am I?",
        "What breaks yet never falls, and what falls yet never breaks?",
        "I can fly without wings. I cry without eyes. Whenever I go, darkness flies. What am I?",
        "I have branches, but no fruit, trunk or leaves. What am I?",
        "What can you catch, but not throw?",
        "I get wetter the more I dry. What am I?",
        "I am taken from a mine, and shut in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?",
        "I have no life, but I can die. What am I?",
        "I can be long, I can be short. I can grow, I can die. I can laugh, I can cry. What am I?",
        "I come from a mine and get surrounded by wood always. Everyone uses me. What am I?",
        "I can be cracked, made, told, and played. What am I?",
        "I can run but not walk. Wherever I go, thought follows close behind. What am I?",
        "I am invisible, weigh nothing, and if you put me in a barrel, it will become lighter. What am I?",
        "I fly without wings. I cry without eyes. Wherever I go, darkness flies. What am I?",
        "I am full of holes but I still hold water. What am I?",
        "What gets bigger the more you take away?",
        "What comes once in a year, twice in a month, four times in a week, and six times in a day?",
        "What belongs to you but others use it more than you do?",
        "I can be cracked, made, told, and played. What am I?",
        "The more of this there is, the less you see. What is it?",
        "I am always coming, but never arrive. What am I?",
        "If you have me, you want to share me. If you share me, you don’t have me. What am I?",
        "What can you hold in your left hand, but not in your right?",
        "What can be seen once in a minute, twice in a moment, and never in a thousand years?",
        "What is always in front of you but can’t be seen?",
        "What has to be broken before you can use it?",
        "I am not alive, but I grow. I don’t have eyes, but I can cry. What am I?",
        "I can be flipped and broken but I never move. I can be closed and open, and sometimes I am curved. What am I?",
        "What begins with T, finishes with T, and has T in it?",
        "What is so fragile that saying its name breaks it?",
        "What comes once in a year, twice in a month, four times in a week, and six times in a day?",
        "I have keys but no locks. I have space but no rooms. You can enter, but you can’t go outside. What am I?",
        "What goes up but never comes down?",
        "What is always in front of you but can’t be seen?",
        "What has many teeth but can’t bite?",
        "What has a head, a tail, but no body?",
        "What gets wet while drying?",
        "I have keys but no locks. I have space but no rooms. You can enter, but you can’t go outside. What am I?",
        "What has one eye, but can’t see?",
        "What has many needles, but doesn’t sew?",
        "What can travel around the world while staying in a corner?",
        "What has legs, but doesn’t walk?",
        "What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?",
        "What comes down but never goes up?",
        "I have teeth but can’t eat. What am I?",
        "What has a neck but no head?",
        "What can be cracked, made, told, and played?",
        "What has words but never speaks?",
        "What has an eye but cannot see?",
        "What has a heart that doesn’t beat?",
        "I am not alive but I can grow. I don’t have eyes but I can cry. What am I?",
        "What has keys but can’t open locks?",
        "What can fill a room but takes no space?",
        "I am taken from a mine and shut in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?",
        "I am full of holes but I still hold water. What am I?",
        "What belongs to you but others use it more than you do?",
        "What gets bigger the more you take away?",
        "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?",
        "What has an eye but cannot see?",
        "What has many keys but can’t open a single lock?",
        "What runs all around a backyard, yet never moves?",
        "What has words, but never speaks?",
        "What can travel around the world while staying in a corner?",
        "I have branches, but no fruit, trunk or leaves. What am I?",
        "What is so fragile that saying its name breaks it?",
        "What is always coming but never arrives?",
        "What can you hold in your left hand, but not in your right?",
        "I get wetter the more I dry. What am I?",
        "I am always in front of you but can’t be seen. What am I?",
        "What breaks yet never falls, and what falls yet never breaks?",
        "What comes once in a year, twice in a month, four times in a week, and six times in a day?",
        "What is always coming but never arrives?",
        "What belongs to you but others use it more than you do?",
        "What has many teeth but can’t bite?",
        "I can run but not walk. Wherever I go, thought follows close behind. What am I?",
        "What can fill a room but takes no space?",
        "What can you catch, but not throw?",
        "What is full of holes but still holds water?"
    ]
